RESULT = a.out
SOURCES = mygraphics.ml a.ml
PACKS = graphics,extlib
INCDIRS =
LIBS =
THREADS =
ANNOTATE = yes
OCAMLFLAGS = -bin-annot -w A

all: debug-code

export OCAMLMAKEFILE = ~/src/ocamlmakefile/OCamlMakefile
include $(OCAMLMAKEFILE)
