RESULT = a.out
SOURCES = a.ml
PACKS = extlib
INCDIRS =
LIBS =
THREADS =
ANNOTATE = yes
OCAMLFLAGS = -bin-annot -w A

all: debug-code

export OCAMLMAKEFILE = ~/src/ocamlmakefile/OCamlMakefile
include $(OCAMLMAKEFILE)
